const trainees = [
  {
    id: 1,
    name: "Francis Adrian Altesing",
    email: "francisadrian.altesing@gmail.com",
    studentId: "202-00005",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-09-12',
    company_id: 1,
  },
  {
    id: 2,
    name: "John Wick",
    email: "ilovedogs143@gmail.com",
    studentId: "202-00006",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: true,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-09-15',
    company_id: 3,
  },
  {
    id: 3,
    name: "Lionel Messi",
    email: "viscabarca10@gmail.com",
    studentId: "202-00007",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-09-18',
    company_id: 4,
  },
  {
    id: 4,
    name: "Cristiano Ronaldo",
    email: "cristiano@gmail.com",
    studentId: "202-00008",
    course: "BSIT",
    year: 4,
    deployed: false,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-09-21',
    company_id: 2,
  },
  {
    id: 5,
    name: "Lebron James",
    email: "LebronJames@gmail.com",
    studentId: "202-00009",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-09-24',
    company_id: 3,
  },
  {
    id: 6,
    name: "Stephen Curry",
    email: "christiano@gmail.com",
    studentId: "202-00010",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-09-15',
    company_id: 2,
  },
  {
    id: 7,
    name: "Kevin Durant",
    email: "KevinDurant@gmail.com",
    studentId: "202-00011",
    course: "BSCS",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-09-15',
    company_id: 5,
  },
  {
    id: 8,
    name: "Michael Jordan",
    email: "Michael23@gmail.com",
    studentId: "202-00012",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-02',
    company_id: 5,
  },
  {
    id: 9,
    name: "Kobe Bryant",
    email: "kobe24@gmail.com",
    studentId: "202-00013",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-05',
    company_id: 1,
  },
  {
    id: 10,
    name: "Shaquille O'Neal",
    email: "shaq34@gmail.com",
    studentId: "202-00014",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-08',
    company_id: 2,
  },
  {
    id: 11,
    name: "Tim Duncan",
    email: "tim21@gmail.com",
    studentId: "202-00015",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-11',
    company_id: 3,
  },
  {
    id: 12,
    name: "Dirk Nowitzki",
    email: "dirk41@gmail.com",
    studentId: "202-00016",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-14',
    company_id: 4,
  },
  {
    id: 13,
    name: "Paul Pierce",
    email: "paul34@gmail.com",
    studentId: "202-00017",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-17',
    company_id: 5,
  },
  {
    id: 14,
    name: "Ray Allen",
    email: "ray20@gmail.com",
    studentId: "202-00018",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-20',
    company_id: 1,
  },
  {
    id: 15,
    name: "Dwyane Wade",
    email: "dwade3@gmail.com",
    studentId: "202-00019",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-23',
    company_id: 2,
  },
  {
    id: 16,
    name: "Chris Bosh",
    email: "chris1@gmail.com",
    studentId: "202-00020",
    course: "BSIT",
    year: 4,
    deployed: true,
    evaluated: false,
    completed: false,
    avatar: "/placeholder.svg",
    required_hours: 486,
    date_started_ojt: '2024-10-26',
    company_id: 3,
  },
];

export default trainees;