const traineeSubmissions = [
    {
      id: 1,
      submissions: [
        { document: 'Student Internship Contract', submitted: false, file_name: null, file_url: null },
        { document: 'Internship Work Plan', submitted: false, file_name: null, file_url: null },
        { document: 'Parents Consent', submitted: true, file_name: 'Parents_Consent_ALTESING.pdf', file_url: '/fake/data/1' },   
        { document: 'Medical Certificate', submitted: true, file_name: 'Medical_Certificate_ALTESING.pdf', file_url: '/fake/data/2' },
        { document: 'Student Pledge', submitted: false, file_name: null, file_url: null },
        { document: 'Departmental Acceptance', submitted: false, file_name: null, file_url: null },
        { document: 'Insurance', submitted: false, file_name: null, file_url: null },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_History_Statement_ALTESING.pdf', file_url: '/fake/data/3' },
      ],
    },
    {
      id: 2,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_WICK.pdf', file_url: '/fake/data/4' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Internship_Work_Plan_WICK.pdf', file_url: '/fake/data/5' },
        { document: 'Parents Consent', submitted: true, file_name: 'Parents_Consent_WICK.pdf', file_url: '/fake/data/6' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Medical_Certificate_WICK.pdf', file_url: '/fake/data/7' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Pledge_WICK.pdf', file_url: '/fake/data/8' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Departmental_Acceptance_WICK.pdf', file_url: '/fake/data/9' },
        { document: 'Insurance', submitted: true, file_name: 'Insurance_WICK.pdf', file_url: '/fake/data/10' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_History_Statement_WICK.pdf', file_url: '/fake/data/11' },
      ],
    },
    {
      id: 3,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_MESSI.pdf', file_url: '/fake/data/12' },
        { document: 'Internship Work Plan', submitted: false, file_name: null, file_url: null },
        { document: 'Parents Consent', submitted: true, file_name: 'Parents_Consent_MESSI.pdf', file_url: '/fake/data/13' },
        { document: 'Medical Certificate', submitted: false, file_name: null, file_url: null },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Pledge_MESSI.pdf', file_url: '/fake/data/14' },
        { document: 'Departmental Acceptance', submitted: false, },
        { document: 'Insurance', submitted: true, file_name: 'Insurance_MESSI.pdf', file_url: '/fake/data/15' },
        { document: 'Student History Statement', submitted: false, file_name: null, file_url: null },
      ],
    },
    {
      id: 4,
      submissions: [
        { document: 'Student Internship Contract', submitted: false, file_name: null, file_url: null },
        { document: 'Internship Work Plan', submitted: false, file_name: null, file_url: null },
        { document: 'Parents Consent', submitted: false, file_name: null, file_url: null },
        { document: 'Medical Certificate', submitted: false, file_name: null, file_url: null },
        { document: 'Student Pledge', submitted: false, file_name: null, file_url: null },
        { document: 'Departmental Acceptance', submitted: false },
        { document: 'Insurance', submitted: false, file_name: null, file_url: null },
        { document: 'Student History Statement', submitted: false, file_name: null, file_url: null },
      ],
    },
    {
      id: 5,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '/fake/data/16' },
      ],
    },
    {
      id: 6,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
        { document: 'Parents Consent', submitted: false, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
        { document: 'Student Pledge', submitted: false, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
        { document: 'Insurance', submitted: false, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '/fake/data/17' },
      ],
    },
    {
      id: 7,
      submissions: [
        { document: 'Student Internship Contract', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Internship Work Plan', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Parents Consent', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Medical Certificate', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Student Pledge', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Departmental Acceptance', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Insurance', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Student History Statement', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
      ],
    },
    {
      id: 8,
      submissions: [
        { document: 'Student Internship Contract', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },,
        { document: 'Internship Work Plan', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Parents Consent', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Medical Certificate', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Student Pledge', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Departmental Acceptance', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Insurance', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Student History Statement', submitted: false,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
      ],
    },
    {
      id: 9,
      submissions: [
        { document: 'Student Internship Contract', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Internship Work Plan', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Parents Consent', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Medical Certificate', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Student Pledge', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Departmental Acceptance', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Insurance', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
        { document: 'Student History Statement', submitted: true,file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '/fake/data/18' },
      ],
    },
    {
      id: 10,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '/fake/data/19' },
      ],
    },
    {
      id: 11,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '/fake/data/20' },
      ],
    },
    {
      id: 12,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '/fake/data/21' },
      ],
    },
    {
      id: 13,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '/fake/data/22' },
      ],
    },
    {
      id: 14,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '/fake/data/23' },
      ],
    },
    {
      id: 15,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '/fake/data/24' },
      ],
    },
    {
      id: 16,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '/fake/data/25' },
      ],
    },
  ];
  
  export default traineeSubmissions;