const traineeSubmissions = [
  {
    id: 1,
    submissions: [
      { document: 'Student Internship Contract', submitted: false, file_name: null, file_url: null },
      { document: 'Internship Work Plan', submitted: false, file_name: null, file_url: null },
      { document: 'Parents Consent', submitted: true, file_name: 'Parents_Consent_ALTESING.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },   
      { document: 'Medical Certificate', submitted: true, file_name: 'Medical_Certificate_ALTESING.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: false, file_name: null, file_url: null },
      { document: 'Departmental Acceptance', submitted: false, file_name: null, file_url: null },
      { document: 'Insurance', submitted: false, file_name: null, file_url: null },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_History_Statement_ALTESING.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 2,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Internship_Work_Plan_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Parents_Consent_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Medical_Certificate_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Pledge_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Departmental_Acceptance_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Insurance_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_History_Statement_WICK.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 3,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_MESSI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: false, file_name: null, file_url: null },
      { document: 'Parents Consent', submitted: true, file_name: 'Parents_Consent_MESSI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: false, file_name: null, file_url: null },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Pledge_MESSI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: false, file_name: null, file_url: null },
      { document: 'Insurance', submitted: true, file_name: 'Insurance_MESSI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: false, file_name: null, file_url: null },
    ],
  },
  {
    id: 4,
    submissions: [
      { document: 'Student Internship Contract', submitted: false, file_name: null, file_url: null },
      { document: 'Internship Work Plan', submitted: false, file_name: null, file_url: null },
      { document: 'Parents Consent', submitted: false, file_name: null, file_url: null },
      { document: 'Medical Certificate', submitted: false, file_name: null, file_url: null },
      { document: 'Student Pledge', submitted: false, file_name: null, file_url: null },
      { document: 'Departmental Acceptance', submitted: false, file_name: null, file_url: null },
      { document: 'Insurance', submitted: false, file_name: null, file_url: null },
      { document: 'Student History Statement', submitted: false, file_name: null, file_url: null },
    ],
  },
  {
    id: 5,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_JAMES.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 6,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: false, file_name: null, file_url: null },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: false, file_name: null, file_url: null },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: false, file_name: null, file_url: null },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_CURRY.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 7,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 8,
    submissions: [
      { document: 'Student Internship Contract', submitted: false, file_name: null, file_url: null },
      { document: 'Internship Work Plan', submitted: false, file_name: null, file_url: null },
      { document: 'Parents Consent', submitted: false, file_name: null, file_url: null },
      { document: 'Medical Certificate', submitted: false, file_name: null, file_url: null },
      { document: 'Student Pledge', submitted: false, file_name: null, file_url: null },
      { document: 'Departmental Acceptance', submitted: false, file_name: null, file_url: null },
      { document: 'Insurance', submitted: false, file_name: null, file_url: null },
      { document: 'Student History Statement', submitted: false, file_name: null, file_url: null },
    ],
  },
  {
    id: 9,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_DURANT.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 10,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_ONEAL.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 11,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_DUNCAN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 12,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_NOWITZKI.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
  {
    id: 13,
    submissions: [
      { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_PIERCE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
    ],
  },
    {
      id: 14,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_ALLEN.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      ],
    },
    {
      id: 15,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_WADE.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      ],
    },
    {
      id: 16,
      submissions: [
        { document: 'Student Internship Contract', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Internship Work Plan', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Parents Consent', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Medical Certificate', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Student Pledge', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Departmental Acceptance', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Insurance', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
        { document: 'Student History Statement', submitted: true, file_name: 'Student_Internship_Contract_BOSH.pdf', file_url: '../assets/files/STUDENT_DETAILS.pdf' },
      ],
    },
  ];
  
  export default traineeSubmissions;