const trainees = [
    {
      id: 1,
      name: "FRANCIS ADRIAN ALTESING",
      email: "francisadrian.altesing@gmail.com",
      studentId: "202-00005",
      course: "BSIT",
      year: 4,
      deployed: true,
      evaluated: false,
      completed: false,
      avatar: "/placeholder.svg",
    },
    {
      id: 2,
      name: "JOHN WICK",
      email: "ilovedogs143@gmail.com",
      studentId: "202-00006",
      course: "BSIT",
      year: 4,
      deployed: true,
      evaluated: false,
      completed: true,
      avatar: "/placeholder.svg",
    },
    {
      id: 3,
      name: "LIONEL MESSI",
      email: "viscabarca10@gmail.com",
      studentId: "202-00007",
      course: "BSIT",
      year: 4,
      deployed: true,
      evaluated: false,
      completed: false,
      avatar: "/placeholder.svg",
    },
    {
      id: 4,
      name: "CRISTIANO RONALDO",
      email: "christiano@gmail.com",
      studentId: "202-00008",
      course: "BSIT",
      year: 4,
      deployed: false,
      evaluated: false,
      completed: false,
      avatar: "/placeholder.svg",
    },
    {
      id: 5,
      name: "Lebron James",
      email: "LebronJames@gmail.com",
      studentId: "202-00009",
      course: "BSIT",
      year: 4,
      deployed: true,
      evaluated: false,
      completed: false,
      avatar: "/placeholder.svg",
    },
    {
      id: 6,
      name: "Stephen Curry",
      email: "christiano@gmail.com",
      studentId: "202-00010",
      course: "BSIT",
      year: 4,
      deployed: true,
      evaluated: false,
      completed: false,
      avatar: "/placeholder.svg",
    },
    {
      id: 7,
      name: "Kevin Durant",
      email: "KevinDurant@gmail.com",
      studentId: "202-00011",
      course: "BSCS",
      year: 4,
      deployed: true,
      evaluated: false,
      completed: false,
      avatar: "/placeholder.svg",
    },
    {
      id: 8,
      name: "Michael Jordan",
      email: "Michael23@gmail.com",
      studentId: "202-00012",
      course: "BSIT",
      year: 4,
      deployed: true,
      evaluated: false,
      completed: false,
      avatar: "/placeholder.svg",
    },
  ];
  
  export default trainees;