const TraineeEvaluationResults = [
  {
    id: 1,
    trainee_id: 1,
    company_id: 1,
    representative_name: "Rick Grimes",
    attendance_punctuality_score: 80,
    performance_score: 85,
    general_attitude_score: 90,
    evaluation_score: (80 + 85 + 90) / 3,
    strengths: "Hardworking and dedicated.",
    weaknesses: "Needs to improve time management.",
    other_comments: "Overall, a very promising trainee."
  },
  {
    id: 2,
    trainee_id: 2,
    company_id: 3,
    representative_name: "Jane Smith",
    attendance_punctuality_score: 88,
    performance_score: 92,
    general_attitude_score: 90,
    evaluation_score: (88 + 92 + 90) / 3,
    strengths: "Excellent problem-solving skills.",
    weaknesses: "Can be too detail-oriented.",
    other_comments: "Great potential for leadership roles."
  },
  {
    id: 3,
    trainee_id: 3,
    company_id: 4,
    representative_name: "Michael Johnson",
    attendance_punctuality_score: 85,
    performance_score: 88,
    general_attitude_score: 91,
    evaluation_score: (85 + 88 + 91) / 3,
    strengths: "Very creative and innovative.",
    weaknesses: "Sometimes lacks focus.",
    other_comments: "A valuable addition to any team."
  },
  {
    id: 4,
    trainee_id: 4,
    company_id: 2,
    representative_name: "John Doe",
    attendance_punctuality_score: 90,
    performance_score: 92,
    general_attitude_score: 94,
    evaluation_score: (90 + 92 + 94) / 3,
    strengths: "Highly motivated and proactive.",
    weaknesses: "Needs to work on communication skills.",
    other_comments: "Shows great potential for growth."
  },
  {
    id: 5,
    trainee_id: 5,
    company_id: 3,
    representative_name: "Jane Smith",
    attendance_punctuality_score: 82,
    performance_score: 87,
    general_attitude_score: 85,
    evaluation_score: (82 + 87 + 85) / 3,
    strengths: "Quick learner and adaptable.",
    weaknesses: "Can be hesitant to ask for help.",
    other_comments: "Overall, a strong performer."
  },
  {
    id: 6,
    trainee_id: 6,
    company_id: 2,
    representative_name: "John Doe",
    attendance_punctuality_score: 85,
    performance_score: 89,
    general_attitude_score: 90,
    evaluation_score: (85 + 89 + 90) / 3,
    strengths: "Great team player.",
    weaknesses: "Needs to improve technical skills.",
    other_comments: "Very reliable and dependable."
  },
  {
    id: 7,
    trainee_id: 7,
    company_id: 5,
    representative_name: "Emily Davis",
    attendance_punctuality_score: 90,
    performance_score: 91,
    general_attitude_score: 92,
    evaluation_score: (90 + 91 + 92) / 3,
    strengths: "Excellent communication skills.",
    weaknesses: "Can be overly critical of own work.",
    other_comments: "A pleasure to work with."
  },
  {
    id: 8,
    trainee_id: 8,
    company_id: 5,
    representative_name: "Emily Davis",
    attendance_punctuality_score: 84,
    performance_score: 86,
    general_attitude_score: 88,
    evaluation_score: (84 + 86 + 88) / 3,
    strengths: "Very organized and efficient.",
    weaknesses: "Needs to work on public speaking.",
    other_comments: "Shows great attention to detail."
  },
  {
    id: 9,
    trainee_id: 9,
    company_id: 1,
    representative_name: "Rick Grimes",
    attendance_punctuality_score: 80,
    performance_score: 84,
    general_attitude_score: 88,
    evaluation_score: (80 + 84 + 88) / 3,
    strengths: "Good analytical skills.",
    weaknesses: "Can be too reserved.",
    other_comments: "Has a lot of potential."
  },
  {
    id: 10,
    trainee_id: 10,
    company_id: 2,
    representative_name: "John Doe",
    attendance_punctuality_score: 92,
    performance_score: 93,
    general_attitude_score: 94,
    evaluation_score: (92 + 93 + 94) / 3,
    strengths: "Very resourceful and independent.",
    weaknesses: "Needs to improve delegation skills.",
    other_comments: "A top performer."
  },
  {
    id: 11,
    trainee_id: 11,
    company_id: 3,
    representative_name: "Jane Smith",
    attendance_punctuality_score: 82,
    performance_score: 85,
    general_attitude_score: 88,
    evaluation_score: (82 + 85 + 88) / 3,
    strengths: "Great at multitasking.",
    weaknesses: "Can be too focused on details.",
    other_comments: "A strong asset to the team."
  },
  {
    id: 12,
    trainee_id: 12,
    company_id: 4,
    representative_name: "Michael Johnson",
    attendance_punctuality_score: 85,
    performance_score: 88,
    general_attitude_score: 90,
    evaluation_score: (85 + 88 + 90) / 3,
    strengths: "Very innovative.",
    weaknesses: "Needs to improve consistency.",
    other_comments: "A creative thinker."
  },
  {
    id: 13,
    trainee_id: 13,
    company_id: 5,
    representative_name: "Emily Davis",
    attendance_punctuality_score: 88,
    performance_score: 90,
    general_attitude_score: 92,
    evaluation_score: (88 + 90 + 92) / 3,
    strengths: "Excellent leadership skills.",
    weaknesses: "Can be too self-critical.",
    other_comments: "A future leader."
  },
  {
    id: 14,
    trainee_id: 14,
    company_id: 1,
    representative_name: "Rick Grimes",
    attendance_punctuality_score: 85,
    performance_score: 87,
    general_attitude_score: 89,
    evaluation_score: (85 + 87 + 89) / 3,
    strengths: "Very diligent and hardworking.",
    weaknesses: "Needs to improve presentation skills.",
    other_comments: "A promising trainee."
  },
  {
    id: 15,
    trainee_id: 15,
    company_id: 2,
    representative_name: "John Doe",
    attendance_punctuality_score: 86,
    performance_score: 89,
    general_attitude_score: 92,
    evaluation_score: (86 + 89 + 92) / 3,
    strengths: "Great at problem-solving.",
    weaknesses: "Can be too focused on perfection.",
    other_comments: "A valuable team member."
  },
  {
    id: 16,
    trainee_id: 16,
    company_id: 3,
    representative_name: "Jane Smith",
    attendance_punctuality_score: 84,
    performance_score: 86,
    general_attitude_score: 88,
    evaluation_score: (84 + 86 + 88) / 3,
    strengths: "Very adaptable.",
    weaknesses: "Needs to improve time management.",
    other_comments: "A strong performer."
  },
];

export default TraineeEvaluationResults;